  version: '3'

  services:
    mongodb:
      image: mongo:6.0.4
      env_file:
        - .env.local
      environment:
        - MONGO_INITDB_DATABASE=${MONGO_DB}
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      restart: on-failure
      ports:
        - 27017:27017
