name: Deploy to DigitalOcean

on:
  workflow_run:
    workflows: Unit Tests
    branches: main
    types: completed

  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

env:
  REGISTRY: "registry.digitalocean.com/ganesha"
  IMAGE_NAME: "ganesha-backend-image"

jobs:
  build_and_push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_PAT }}

    - name: Build container image
      run: docker build $(buildargs.sh .env.beta) -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest .

    - name: Login DigitalOcean Container Registry
      run: doctl registry login --expiry-seconds 1200

    - name: Remove all old images
      run: if [ ! -z "$(doctl registry repository list | grep "$(echo $IMAGE_NAME)")" ]; then doctl registry repository delete-manifest $(echo $IMAGE_NAME) $(doctl registry repository list-tags $(echo $IMAGE_NAME) | grep -o "sha.*") --force; else echo "No repository"; fi

    - name: Push image to DigitalOcean Container Registry
      run: |
        docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
        docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy on Droplet
      run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
        docker rmi ganesha-backend-web
        docker rmi registry.digitalocean.com/ganesha/dev
        docker-compose -f docker-compose.beta.yml build
        docker image ls | grep ganesha-backend-web
        doctl registry login --expiry-seconds 1200
        docker tag ganesha-backend-web registry.digitalocean.com/ganesha/dev
        docker push registry.digitalocean.com/ganesha/dev
      EOF

